sudo: required

services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty

before_install:

  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  - docker ps
  - docker info
  - docker version

  - docker pull commonsearch/local-elasticsearch
  - docker run -d -p 39200:9200 -p 39300:9300 commonsearch/local-elasticsearch

  # Docker cannot use the build cache after a pull anymore!
  # This will make the build much slower until there is a practical workaround :(
  # https://github.com/docker/docker/issues/20316
  #
  # - docker pull commonsearch/local-back
  # - docker inspect commonsearch/local-back
  # - docker history commonsearch/local-back
  # - ./scripts/git-set-file-times

  - docker build -t commonsearch/local-back .
  - ps -ef
  - netstat -lpn
  - docker run commonsearch/local-back ip route show 0.0.0.0/0
  - docker run commonsearch/local-back cat /etc/hosts
  - curl "http://127.0.0.1:39200"
  - docker run -e COSR_ELASTICSEARCHTEXT commonsearch/local-back curl $COSR_ELASTICSEARCHTEXT

script:
  - make docker_pylint
  - make docker_test_coverage
